### ISSUE TITLE
Healfie - Entering Health Parameter values for more than 2 entries misplaces the values of weight parameter and make Weight parameter value as empty

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-Android#11]
## Steps To Reproduce:

Case 1:
1. Click on the camera icon to create a new healfie.
2. Add Health parameters Weight, Waist C and Sleep (any parameter with slider selection) 
3. Enter Weight value as 60, Waist value as 150.
4. Click on sleep parameter to enter the value for it.

Case 2:
Follow same steps in case 1. try deleting the Weight value to empty still displays as '6' near the info icon and for all the parameters where input value is needed to enter (not in sliders)
## Actual Result:

Case 1:
The Weight value is displayed in the Sleep parameter and Weight parameter is made empty.
Changing the sleep value then changes it. still Weight field is empty

Case 2:
deleting the Weight value to empty still displays as '6' near the info icon and for all the parameters where input value is needed to enter (not in sliders)
## Expected Result:

Case 1:
The values should be displayed correspondingly.

Case 2:
The values should be deleted completely if the user clears the fields.

**Comment by narayanasprim** [comment]
Mobile defend to displaying...

**Comment by shanthasprim** [comment]
Case 1 is not reproducible
Case 2 Still reproducible

**Comment by hanusprim** [comment]
Issue is fixed
