### ISSUE TITLE
Healfie - Entering the health parameter values and then changing the Healfie picture or Healfie Profile removes the entered health parameter values

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-Android#14]
## Steps To Reproduce:
1. Click on the camera icon to add a new healfie.
2. Add and Enter values for the health parameters 
3. Before saving the healfie, try changing the Profile name or the Healfie pic
## Actual Result:

The health parameter values are removed and the fields are made empty
## Expected Result:

The health parameter values should not be removed

**Comment by hanusprim** [comment]
In this scenario,User mandatory to save his profile picture,not health parameters values..for this reason all the parameters going to be refresh and empty fields.
