### ISSUE TITLE
Left Menu - Rename Left Menu item "All Profiles" to "Dashboard"

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-Android#2]
## Steps To Reproduce:
1. Open the left menu in the Healfie app
2. Check the left menu items
## Actual Result:

The first item is displayed as "All Profiles" 
## Expected Result:

"All Profiles" left menu item should be renamed as "Dashboard"

**Comment by narayanasprim** [comment]
#2 Fixed

**Comment by shanthasprim** [comment]
Name is changed. Hence closing the issue.
