### ISSUE TITLE
Healfie - Entering Health Parameter values opens the correct keypad only after touching the text box for second time

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-Android#5]
## Steps To Reproduce:
1. Add a healfie value
2. Add any health parameter values (Weight, Waist C or Fitness)
3. Click on the Weight text box to add the new value
## Actual Result:

First click opens the keypad with alphabets which on second click opens the keypad with numbers
## Expected Result:

Keypad with numbers should open on the first click

**Comment by shanthasprim** [comment]
The keypad opens correctly now. But the input field gets hided under the keypad except the first field.
User cannot view what value entered for the health parameters

**Comment by hanusprim** [comment]
Issue Closed

**Comment by shanthasprim** [comment]
Working as Expected now. Hence closing the issue.
